{
 "title": "ENC[AES256_GCM,data:Ha4ZIUjl,iv:wRXA/DX7NOhKWFbvbfnTeNlLYsWrGjiFhtf7o/x3nHE=,tag:R96w+5pXtcp2hXXidd3Qzg==,type:str]",
 "time": {
  "from": "ENC[AES256_GCM,data:pwcOArAe,iv:9aMpaWeeXGgB06+7MEp3r2+SiqMu180sfdL3H1vHd+o=,tag:qko9hnh8E416wwcbNYmTXg==,type:str]",
  "to": "ENC[AES256_GCM,data:HDM8,iv:1PRr+akV35YjeoJT2c+WQCfOKCpPBolNCBeaXpVh3cw=,tag:SB8lRRei2goHqwKcZBsR4Q==,type:str]"
 },
 "panels": [
  {
   "title": "ENC[AES256_GCM,data:SXRKG0kt8B0QLdbYOi2jmwd1WnZmzk5EnHS4PqKzwDpxiz2b,iv:agyGRb4zq25FK0TfoOZ9D3H5nEen1sF68WZFyH7Gmy8=,tag:45NnjRzfYH9k8dV3k3Kx8A==,type:str]",
   "type": "ENC[AES256_GCM,data:K9qtmKYLac6Xxg==,iv:kBFi8b47FNDTaMliLnWg1PYeTw7nLvKwhm83mJRZc9w=,tag:oOkJv2S2ZgaC2mNtzxyJ4g==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:KQ==,iv:s2x+CYDnWX4n6uaYeEZOzBskI6/5v+QugJZP3FV+3IQ=,tag:CLagDFLrLaDxOqIPQA+CTA==,type:float]",
    "w": "ENC[AES256_GCM,data:OXg=,iv:1b/A/Zl3L08O2Kfu8g7EhW6uR9uRWEOfXezWMmUTUCI=,tag:B8ILWXRhdcmNYamOChFQHA==,type:float]",
    "x": "ENC[AES256_GCM,data:Ew==,iv:DFYj9sriZZr4e5WbY39HxOk2Vo6yOWvZnu46zXSsYjs=,tag:iCyK1qd1CAOaYo07uPideg==,type:float]",
    "y": "ENC[AES256_GCM,data:TA==,iv:q/r8j1qfOhIARuhHWARiQ/n/2dfMe+/PNsWONL2n0Vo=,tag:eXFeqviudX4LTrml5KJPgw==,type:float]"
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:tIw8ofKiJXDTeQ9pwk8XIblhL35FHgGzZGE=,iv:d5kdutURXokGUfSTKNY66UNPYX8/u81uQ+bvfPcffHM=,tag:/fF0Pofhi5bif3escmYxWw==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:87p4BOW6,iv:ig7szLyPhqhHK9bJLQSAiGC7VCfvKRG4DBxiGYA48W8=,tag:82QClc750EjP6xYPNFs+OQ==,type:str]"
    }
   ]
  },
  {
   "title": "ENC[AES256_GCM,data:h/N1mL5bSR54HBU=,iv:vPYug4dLhEvrWR3+94W6FDFMuvrDG+vSv2q/EH+YeD4=,tag:e+GBkduJ/+Op0EGC3f+k7w==,type:str]",
   "type": "ENC[AES256_GCM,data:zcn0nTg0GlLHDg==,iv:k8Yd+PhnOAbyz3VBm/oHJpa6/95/GB8UWMjJ8bNy8mU=,tag:wSeRUNwHY0Ffr2HmmFVZgg==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:5g==,iv:ZeddDOESd67a9/pbKtGHG3o3/WuOQYtTY8UikPcq4BQ=,tag://G3wQEylqBxHhQOGfmDKA==,type:float]",
    "w": "ENC[AES256_GCM,data:3vA=,iv:VpDEEQ/ZXGQiUASAL28K5RQsqNJJMDOToKfi0tDGcss=,tag:F4ZOFjEJHVJjk8dCrwx9mA==,type:float]",
    "x": "ENC[AES256_GCM,data:9/g=,iv:5Ll9WurUj/iF3l7XG/n5Mm08+eUzYTUjRJBHatmDF58=,tag:spDHfD8t6d5+QJtbDzuDYg==,type:float]",
    "y": "ENC[AES256_GCM,data:rw==,iv:kj8f8kOEeTZ21Kdj4buySDFVj+BTeYE8Sh6MwaoYPuA=,tag:hnUaKl8D0scDLI8zcGhNjw==,type:float]"
   },
   "fieldConfig": {
    "defaults": {
     "unit": "ENC[AES256_GCM,data:4yqGnZ0AJSOi,iv:PWijL1lFFiQrWUktTHvmMrGKCuyR0BOpHWt8ozEEO1Y=,tag:70QSrdet83WhDUpKlTZ0BQ==,type:str]"
    }
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:vFLciDE98kiO4j9LGsiUzG64j4HLxMuX7Ig7+oQEnmysMRIJxcP9,iv:UWBnT2Eq2dWwuehLZDogSNbxagBQ30nRwh6dRjcSjn0=,tag:naNT1I+HgZHpDpifGUCM+g==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:ZwRJPXYD,iv:DYGTbZ+wErvPrQc8Q6Cx0ezvPoD8SETFmXl03puAFxQ=,tag:xt2o1iYj9S/m7nPUn6l9hA==,type:str]"
    }
   ]
  },
  {
   "title": "ENC[AES256_GCM,data:/2X3sGyVZoZBmw3HmYVF7FFvQHp/,iv:reOjW2qPHPXQcZ1iirCCj/hZGTgboTsd2ADGYvcYkx0=,tag:Um8KBkElYhlwONEwEMg1pg==,type:str]",
   "type": "ENC[AES256_GCM,data:QVx9rFXHFezgpw==,iv:xuxdiqq++/QrOUNgaRkBVKOCusEyFZ1g2RxIf05f83E=,tag:LlqPgUwqBj3/I65M8DpxeA==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:qw==,iv:yPzsWV9C5NoZvGaeiDvIpWQQ/b2XJOa3twQfeZpdTi0=,tag:lzm3q/DC5NeNJWs7XnjPdw==,type:float]",
    "w": "ENC[AES256_GCM,data:rac=,iv:a/Tc8gbkSPuMgj65rVkEngKSF6pUCb6ZzxMvZVr/gRk=,tag:KauzzZIHWnp9s0AZ4Hnexg==,type:float]",
    "x": "ENC[AES256_GCM,data:Lw==,iv:qwGcrNnt3uJbmxeTg/E1r9dKJt+idy6MlzGdWzJIbIY=,tag:Km+IUGY+kmbsROb1DX6BDg==,type:float]",
    "y": "ENC[AES256_GCM,data:qg==,iv:eDUcaHvufojxRnHkNItSIPTjC7rM2a/sARqNyGmaybU=,tag:TlfiT/uCmNONcTxejTTR/w==,type:float]"
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:R8csMABdLjqg2SqR0kQy3DMZEK6iDDucY55Kv/T+9mhh3xU+,iv:LZn5j9YhbGQbSIMlKLMiveAfsOar/w/su01wg0O7geU=,tag:/BF5JbOkpkMu95JD+tK12Q==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:mKDSmQNW,iv:9TvFOhjcFeyBmRKIgH13dAEh0yUNSK4bSkhvWU1J2nY=,tag:Dw3vX7Ddm4cClB2LSJ7ULg==,type:str]"
    }
   ]
  }
 ]
}