{
 "title": "ENC[AES256_GCM,data:vwa4Q/Vs,iv:viXlmSojfEIj5hnWZzw/m7cPupMffHALRA/7rLxgo0k=,tag:/M6MAtVuNA5W5fvYkY+gaA==,type:str]",
 "time": {
  "from": "ENC[AES256_GCM,data:myNtDBqC,iv:x3OxkKzVox+XKu80c3BRUneoBMDUaXUbI4C2I7tGe9Q=,tag:8siJ1D9mb09UNDqOA9x6Zg==,type:str]",
  "to": "ENC[AES256_GCM,data:hK8X,iv:64SBVe2FCI53vOJDNMrQq8p6ixnTZsDUMe1wGQYYLNM=,tag:AHRMi7XE1DW3VAm90MHdKQ==,type:str]"
 },
 "panels": [
  {
   "title": "ENC[AES256_GCM,data:LcTcCoxcNckki7PDeZFR7eg3NtTQu/MDzD6OBVnVftdH48iY,iv:j2Mo2w1qlU+H56FFoOaoqY8NyYI6aRXUYgKivjO2kB4=,tag:J9bDMNlGY/FuFy0n80CaHg==,type:str]",
   "type": "ENC[AES256_GCM,data:+uhPIDVsz/lOfQ==,iv:qsfxjH2iw3Bve0JUotOlnwfbBVRpCPAn/VnSs6K/Egg=,tag:uX+AB3NLxmtcQQ6/1xjoOQ==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:tA==,iv:TjsY1M+bqRXsN0dAAm5+fiBlE+1so/efBk4aYPr1iRE=,tag:GskBk5RJQ3WSGsDK12akFw==,type:float]",
    "w": "ENC[AES256_GCM,data:e+M=,iv:whzMDzRrEn8dG0PfvKaD+aTD1Kyu+TGjzeIp+HoCLL8=,tag:LfFKSxt5V8po0JsoOqB3fA==,type:float]",
    "x": "ENC[AES256_GCM,data:aA==,iv:GPDAQQadrGI04n0FgVr3CloGam8A2WFjivpSQv5xKdI=,tag:X5ZAeClx9hqYjvWD+QtTEA==,type:float]",
    "y": "ENC[AES256_GCM,data:KA==,iv:yaTKeHWVJTp4yqHPevn8YDT+u3Ut3trmGJly17Rkzms=,tag:CmIHxxnV3onmHw8X13oDhw==,type:float]"
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:+s/jwGUsFpDIf65/W6RlC7659knZCH8iJzk=,iv:LOPZnu4W16cjaZtNj3m1Gd0LmdpYM/EMWoQOAWxbjVc=,tag:coofJuruq3UeCQJR1qj/lA==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:t2ROXxQJ,iv:ULNOmKRyGaF1zZjmBaLPGUrlwFbGNLJtr4jDFcpptO0=,tag:n4dNkGVWSn4iHcGMBgWbAQ==,type:str]"
    }
   ]
  },
  {
   "title": "ENC[AES256_GCM,data:wF88bm9OXVCitI8=,iv:4XRoC0iuHJPIRzcgp9nThAx+FdXnIzxfF70i1QBi7Hg=,tag:o9OhRax/gAo0D5eBBAbrhw==,type:str]",
   "type": "ENC[AES256_GCM,data:GQXOPVXpc/K0Qw==,iv:dHG39lLUi4IMfO0ElZz48D1CihNZX0NC5RVLizqXwRE=,tag:uoZylXx7m7x7MWgu6DswwQ==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:gQ==,iv:OT3nxkjnY/RiPTQJHDLHT3HkvJmQi3EB3GjKSa08+sw=,tag:HZJdMUbe+ISM8bv25K7dQA==,type:float]",
    "w": "ENC[AES256_GCM,data:a84=,iv:ecYn6cJmZLN5hsHOghSiNVmkAKI2lL/OrbOeSKoGyZ0=,tag:pEyXfVShCQO6QHyaLp0mgg==,type:float]",
    "x": "ENC[AES256_GCM,data:DWg=,iv:XdXy06M/nhb+D4KaRF2uMfu+lkVUNBthOryVULLdZbo=,tag:WanW8gsP73kUmK/P11Gn9g==,type:float]",
    "y": "ENC[AES256_GCM,data:gg==,iv:Rts8I0dEkH3GTm5N8PMYFOY2xRIR5+KgV9aCaDEy7Lk=,tag:gV9qvggBpyu1dSGcGt3FZA==,type:float]"
   },
   "fieldConfig": {
    "defaults": {
     "unit": "ENC[AES256_GCM,data:Rie+avz2/LoY,iv:gK2b2S/I//bbV/9m1yIUryyhOtw9Uz+s6gbUwxv7L3s=,tag:kXOirBp/U35NCPX/+rx5dQ==,type:str]"
    }
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:pkUA5o/eWxr+OGH9brN9pPBVNx/Un8emIXuG08Kn7rB6iTG/idXU,iv:kJmioQqa5OLp6BFBfWm/IEIq+HmmQH/tfoT+WibXpjM=,tag:duFQm+To2hyfMPnfNw9VQA==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:wsoQxGG7,iv:dbKU8U1zv+Fcc0bUAyjl7LhNRZgj4hzl7/A8KCmBXIY=,tag:PmV0OW9fpXje/4uqPE8cQw==,type:str]"
    }
   ]
  },
  {
   "title": "ENC[AES256_GCM,data:qK6LYNH402xhbn3OCheBnyYk8Olq,iv:LNIzQk+dRNGsKydV0pVOSS5S0ruqyBi6IzKrUBGbhbg=,tag:Hz13DcG2gGZ9bahvsZ22zA==,type:str]",
   "type": "ENC[AES256_GCM,data:s5dX8aLlM9YSjg==,iv:8zgCEdy3JYPPJKOTGuxt+GVvA4/e3EaxvqBuRzfNZ/M=,tag:d3Fnt7O3ozyJskaM/Jbjsg==,type:str]",
   "gridPos": {
    "h": "ENC[AES256_GCM,data:+g==,iv:2WzNOA8Igg7nHb6dia88Q0eFBHXJ9b4ElNl6Fd3iv+Y=,tag:klNtQlQotaMCFYybrbnRgQ==,type:float]",
    "w": "ENC[AES256_GCM,data:Z4Y=,iv:VTJzyN6d2nF5IUBGCeL3mfdLdOsdRMYrBsOS4gVIyic=,tag:ZceeDdvoDPUTtyUQr87nyg==,type:float]",
    "x": "ENC[AES256_GCM,data:TA==,iv:req4Q88AsXe/tkk2gHqJMxlP98Oyyvb0b/lQQ1ubJvo=,tag:f86zIqJZRac32jQ1KgkUhg==,type:float]",
    "y": "ENC[AES256_GCM,data:Hw==,iv:6AbpqXkjPZIawHtcLjX3Al9Kpxb8BxBmz0KRpaspBUU=,tag:PdMSF7R3/Wk5JxwdhAbyXw==,type:float]"
   },
   "targets": [
    {
     "expr": "ENC[AES256_GCM,data:OmhXFgD0eH4wvTfxriUdEDFYm9cf3HXWmQjNstf10KgWdi91,iv:yPTBUdBCuXM7jHpcANIRb0oJtpXoMLTz7nA8yOQ61UA=,tag:BzOLhjOkyeJ+Uyh7B0xoSw==,type:str]",
     "legendFormat": "ENC[AES256_GCM,data:zW91ElpA,iv:3tm2t9h0OcnUXsyl3brLG+bn6WrlhoXU4VUnM7AqZjE=,tag:RSGG79j4UL9DZxtGebEOkA==,type:str]"
    }
   ]
  }
 ]
}