version: '3.7'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - otel-collector
    ports:
      - "8080:8080"
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - "--config=/etc/otel-collector.yaml"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://tempo-prod-04-prod-us-east-0.grafana.net:443
      - OTEL_EXPORTER_OTLP_AUTHORIZATION=${OTEL_EXPORTER_OTLP_AUTHORIZATION} # Replace with the result of $(echo tempo_username:ap_token | base64)
    ports:
      - "4318:4318"
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
